name: Locale Sync
on:
  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:
  Sync:
    runs-on: ubuntu-latest
    permissions: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Locale Sync
        run: python scripts/sync_locales.py

      - name: Set commiter
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "actions-bot"

      - name: Push
        run: |
          git add .
          git commit -m "Locale Sync"
          git push